#pragma once

// Generated by assets/renderGameFont.py.
constexpr int getFontSpriteAdvanceWidth(int spriteIndex)
{
    switch (spriteIndex) {
    case 0: return 6;
    case 1: return 1;
    case 2: return 2;
    case 3: return 2;
    case 4: return 2;
    case 5: return 3;
    case 6: return 1;
    case 7: return 2;
    case 8: return 5;
    case 9: return 2;
    case 10: return 4;
    case 11: return 4;
    case 12: return 5;
    case 13: return 4;
    case 14: return 5;
    case 15: return 4;
    case 16: return 5;
    case 17: return 5;
    case 18: return 5;
    case 19: return 5;
    case 20: return 5;
    case 21: return 5;
    case 22: return 5;
    case 23: return 4;
    case 24: return 5;
    case 25: return 5;
    case 26: return 2;
    case 27: return 4;
    case 28: return 5;
    case 29: return 4;
    case 30: return 5;
    case 31: return 5;
    case 32: return 6;
    case 33: return 5;
    case 34: return 5;
    case 35: return 5;
    case 36: return 5;
    case 37: return 5;
    case 38: return 5;
    case 39: return 5;
    case 40: return 7;
    case 41: return 5;
    case 42: return 5;
    case 43: return 5;
    case 44: return 6;
    case 45: return 5;
    case 46: return 4;
    case 47: return 5;
    case 48: return 4;
    case 49: return 2;
    case 50: return 4;
    case 51: return 7;
    case 52: return 2;
    case 53: return 4;
    case 54: return 4;
    case 55: return 4;
    case 56: return 1;
    case 57: return 8;
    case 58: return 1;
    case 59: return 2;
    case 60: return 2;
    case 61: return 2;
    case 62: return 3;
    case 63: return 2;
    case 64: return 3;
    case 65: return 7;
    case 66: return 3;
    case 67: return 6;
    case 68: return 6;
    case 69: return 6;
    case 70: return 6;
    case 71: return 7;
    case 72: return 6;
    case 73: return 6;
    case 74: return 7;
    case 75: return 7;
    case 76: return 7;
    case 77: return 7;
    case 78: return 7;
    case 79: return 6;
    case 80: return 6;
    case 81: return 7;
    case 82: return 7;
    case 83: return 3;
    case 84: return 5;
    case 85: return 7;
    case 86: return 6;
    case 87: return 7;
    case 88: return 7;
    case 89: return 8;
    case 90: return 7;
    case 91: return 7;
    case 92: return 7;
    case 93: return 6;
    case 94: return 7;
    case 95: return 7;
    case 96: return 7;
    case 97: return 10;
    case 98: return 7;
    case 99: return 7;
    case 100: return 7;
    case 101: return 8;
    case 102: return 6;
    case 103: return 6;
    case 104: return 5;
    case 105: return 5;
    case 106: return 3;
    case 107: return 6;
    case 108: return 9;
    case 109: return 2;
    case 110: return 6;
    case 111: return 6;
    case 112: return 6;
    case 1335: return 4;
    case 1336: return 2;
    case 1337: return 1;
    case 1338: return 4;
    case 1339: return 4;
    case 1340: return 3;
    case 1341: return 5;
    case 1342: return 5;
    case 1343: return 4;
    case 1344: return 4;
    case 1345: return 2;
    case 1346: return 3;
    case 1347: return 4;
    case 1348: return 6;
    case 1349: return 4;
    case 1350: return 5;
    case 1351: return 4;
    case 1352: return 4;
    case 1353: return 3;
    case 1354: return 2;
    case 1355: return 6;
    case 1356: return 5;
    case 1357: return 4;
    case 1358: return 7;
    case 1359: return 5;
    case 1360: return 7;
    case 1361: return 6;
    case 1362: return 6;
    case 1363: return 2;
    case 1364: return 3;
    case 1365: return 5;
    case 1366: return 8;
    case 1367: return 6;
    case 1368: return 6;
    case 1369: return 6;
    case 1370: return 4;
    case 1371: return 4;
    case 1372: return 6;
    case 1373: return 3;
    case 1374: return 4;
    case 1375: return 2;
    case 1376: return 2;
    case 1377: return 2;
    case 1378: return 2;
    case 1379: return 3;
    case 1380: return 3;
    case 1381: return 2;
    case 1382: return 3;
    case 1383: return 2;
    case 1384: return 2;
    case 1385: return 2;
    case 1386: return 2;
    default: return 0;
    }
}

constexpr uint32_t kSmallFontPairSpacing[] = {
    0x0286bfbb,
    0x0287bfbf,
    0x036d0c05,
    0x0297ffff,
    0x00000000,
    0x03ffffff,
    0x03ffffff,
    0x02000001,
    0x00000000,
    0x03ffffff,
    0x00000000,
    0x0286bfbb,
    0x03ffffff,
    0x02000001,
    0x00000000,
    0x00000000,
    0x0297ffff,
    0x00000000,
    0x00000000,
    0x00000000,
    0x03ffffff,
    0x03fffdfe,
    0x037ffdfe,
    0x02050c01,
    0x037ffdf4,
    0x020c0c01,
};

constexpr uint32_t kBigFontPairSpacing[] = {
    0x0286bfbb,
    0x02878e33,
    0x03ef8e33,
    0x0297ffff,
    0x03ffffff,
    0x03fffdfe,
    0x03ffffff,
    0x01000001,
    0x00000000,
    0x03ffffff,
    0x00000000,
    0x0286bfbb,
    0x03ffffff,
    0x03e90001,
    0x00000000,
    0x00000000,
    0x0287ffbf,
    0x00000000,
    0x03ffffff,
    0x01200000,
    0x03ffffff,
    0x03fffdfe,
    0x016e8c32,
    0x03ec0c31,
    0x03fffdfe,
    0x03a00001,
};

constexpr int getFontPairSpacing(unsigned char current, unsigned char next, bool bigFont)
{
    current |= 0x20;
    next |= 0x20;
    if (current < 'a' || current > 'z' || next < 'a' || next > 'z')
        return 0;

    auto mask = bigFont ? kBigFontPairSpacing[current - 'a'] : kSmallFontPairSpacing[current - 'a'];
    return mask >> (next - 'a') & 1;
}
