<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>SWOS menu description</string>
        <key>scopeName</key>
        <string>source.mnu2h</string>

        <key>fileTypes</key>
        <array>
            <string>mnu</string>
            <string>mh</string>
        </array>

        <key>uuid</key>
        <string>d642d39b-a949-4100-be98-64c5995d5daa</string>

        <key>foldingStartMarker</key>
        <string>\{\s*$</string>
        <key>foldingStopMarker</key>
        <string>^\s*\}</string>

        <key>patterns</key>
        <array>
            <!-- comments -->
            <dict>
                <key>begin</key>
                <string>(^[ \t]+)?(?=//)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.whitespace.comment.leading.mnu2h</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(?!\G)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>//</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.mnu2h</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>\n</string>
                        <key>name</key>
                        <string>comment.line.number-sign.mnu2h</string>
                    </dict>
                </array>
            </dict>

            <!-- preprocessor -->
            <dict>
                <key>match</key>
                <string>\#(include|textWidth|textHeight|repeat|endRepeat|join|print|warningsOn|warningsOff|allowZeroWidthHeightEntries|i|j|k)\b</string>
                <key>name</key>
                <string>entity.other.attribute-name.pragma.preprocessor.c</string>
            </dict>

            <!-- menus and entries -->
            <dict>
                <key>match</key>
                <string>\b(Menu|Entry|TemplateEntry|ResetTemplate)\b(?:\s*([_\w][_\w\d]*))?</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag.mnu2h</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.mnu2h</string>
                    </dict>
                </dict>
            </dict>

            <!-- entry alias -->
            <dict>
                <key>match</key>
                <string>^\s*(entryAlias)(?:\s+([_\w][_\w\d]*)\s*(=)\s*([_\w][_\w\d]*)?)?</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.other.attribute-name.pragma.preprocessor.c</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.mnu2h</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.mnu2h</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.mnu2h</string>
                    </dict>
                </dict>
            </dict>

            <!-- strings -->
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.mnu2h</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.mnu2h</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.mnu2h</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.mnu2h</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>'</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.mnu2h</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.single.mnu2h</string>
            </dict>

            <!-- export keyword -->
            <dict>
                <key>match</key>
                <string>export\b</string>
                <key>name</key>
                <string>entity.other.attribute-name.pragma.preprocessor.c</string>
            </dict>

            <!-- constants -->
            <dict>
                <key>name</key>
                <string>constant.numeric.hex.mnu2h</string>
                <key>match</key>
                <string>\b0(x|X)[0-9a-fA-F_]+(U|u|L|l|UL|Ul|uL|ul|LU|Lu|lU|lu)?\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b\d+\b</string>
                <key>name</key>
                <string>constant.numeric.decimal.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?x)@(
                    kNoBackground|kNoFrame|kGray|kDarkBlue|kLightBrownWithOrangeFrame|kOrangeWithOrangeFrame|kLightBrownWithYellowFrame|kRed|kPurple|
                    kLightBrownWithRedFrame|kLightBlue|kGreen|
                    kGrayFrame|kWhiteFrame|kBlackFrame|kBrownFrame|
                    kLightBrownFrame|kOrangeFrame|kDarkGrayFrame|kNearBlackFrame|
                    kVeryDarkGreenFrame|kRedFrame|kBlueFrame|kPurpleFrame|
                    kSoftBlueFrame|kGreenFrame|kYellowFrame|
                    kDarkGrayText|kWhiteText|kBlackText|kBrownText|
                    kLightBrownText|kOrangeText|kGrayText|kNearBlackText|
                    kVeryDarkGreenText|kRedText|kBlueText|kPurpleText|
                    kSoftBlueText|kGreenText|kYellowText|
                    kCenterAligned|
                    kLeftAligned|kRightAligned|kShowText|kBlinkText|
                    kBigText|kBigFont|
                    kNoEntry|kLeft|kRight|kUp|kDown|
                    kNullText|kNull|
                    previousX|prevX|previousY|prevY|
                    previousEndX|prevEndX|previousEndY|prevEndY|
                    previousWidth|prevWidth|previousHeight|prevHeight|
                    previousOrdinal|previousOrd|prevOrdinal|prevOrd|
                    currentOrdinal|currentOrd|curOrdinal|curOrd|
                    nextOrdinal|nextOrd|
                    kControlFire|kControlShortFire|
                    kControlLeft|kControlRight|kControlUp|kControlDown|
                    kScreenWidth|kScreenHeight|
                    kAlloc|kTextWidth|kTextHeight)\b
                </string>
                <key>name</key>
                <string>punctuation.definition.keyword.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>@[_\w\d]+</string>
                <key>name</key>
                <string>invalid.illegal.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?:(true)|(false))\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>constant.language.boolean.true.mnu2h</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>constant.language.boolean.false.mnu2h</string>
                    </dict>
                </dict>
            </dict>

            <!-- preprocessor symbols -->
            <dict>
                <key>match</key>
                <string>(?&lt;!\w)(:[a-zA-Z_][\w]*)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag.mnu2h</string>
                    </dict>
                </dict>
            </dict>

            <!-- operators -->
            <dict>
                <key>match</key>
                <string>--</string>
                <key>name</key>
                <string>keyword.operator.decrement.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\+\+</string>
                <key>name</key>
                <string>keyword.operator.increment.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>%=|\+=|-=|\*=|(?&lt;!\()\/=</string>
                <key>name</key>
                <string>keyword.operator.assignment.compound.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>&amp;=|\^=|&lt;&lt;=|&gt;&gt;=|\|=</string>
                <key>name</key>
                <string>keyword.operator.assignment.compound.bitwise.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>&lt;&lt;|&gt;&gt;</string>
                <key>name</key>
                <string>keyword.operator.bitwise.shift.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>!=|&lt;=|&gt;=|==|&lt;|&gt;</string>
                <key>name</key>
                <string>keyword.operator.comparison.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>&amp;&amp;|!|\|\|</string>
                <key>name</key>
                <string>keyword.operator.logical.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>&amp;|\||\^|~</string>
                <key>name</key>
                <string>keyword.operator.mnu2h</string>
            </dict>
            <dict>
                <key>match</key>
                <string>%|\*|\/|-|\+</string>
                <key>name</key>
                <string>keyword.operator.mnu2h</string>
            </dict>
            <!-- mark {}, [], :, = grayish too -->
            <dict>
                <key>match</key>
                <string>\+|-|\*|\/|\{|\}|\[|\]|:|=|\#(?=\{)</string>
                <key>name</key>
                <string>keyword.operator.arithmetic.mnu2h</string>
            </dict>

            <!-- properties -->
            <dict>
                <key>match</key>
                <string>(?x)\b(
                    onInit|onReturn|onRestore|onDraw|onDestroy|initialEntry|x|y|defWidth|defaultWidth|defHeight|defaultHeight|
                    defX|defaultX|defY|defaultY|defaultColor|defaultTextFlags|
                    defaultLeftEntry|defaultRightEntry|defaultUpEntry|defaultDownEntry|defaultTopEntry|defaultBottomEntry|
                    menuX|menuY|width|height|ordinal|name|color|textFlags|controlMask|
                    text|stringTable|multilineText|boolOption|number|sprite|menuSpecificSprite|customDrawForeground|customDrawBackground|
                    func1|invisible|disabled|directionLeft|directionRight|directionUp|directionDown|
                    leftEntry|rightEntry|upEntry|downEntry|topEntry|bottomEntry|skipLeft|skipRight|skipUp|skipDown|
                    onSelect|beforeDraw|onReturn|customDrawBackground|customDrawForeground)\s*(?=:)
                </string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.label</string>
                    </dict>
                </dict>
            </dict>

            <!-- variables -->
            <dict>
                <key>match</key>
                <string>^\s*(export\s*)?([_\w][_\w\d]*(?:\s*\.\s*[_\w][\w\d]*)?)\s*(?==[\s_\w\d])</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.other.attribute-name.pragma.preprocessor.c</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language.mnu2h</string>
                    </dict>
                </dict>
            </dict>
        </array>
    </dict>
</plist>
