// automatically generated by ida2asm [don't edit!]

#pragma once

#include "swos.h"

#pragma pack(push, 1)
struct Register
{
    Register(byte b) : data(b) {}
    Register(word w) : data(w) {}
    Register(dword d) : data(d) {}
    Register(int i) : data(i) {}
    Register(const char *p) : data(reinterpret_cast<dword>(p)) {}
    template <typename T> Register(T t) { assign<T>(t); }
    template <typename T> void assign(typename std::enable_if<std::is_convertible<T, dword>::value, T>::type t) {
        data = static_cast<dword>(t);
    }
    template <typename T> void assign(typename std::enable_if<!std::is_convertible<T, dword>::value, T>::type t) {
        data = reinterpret_cast<dword>(t);
    }
    word asWord() const { return static_cast<word>(data); }
    dword asDword() const { return static_cast<dword>(data); }
    int asInt() const { return static_cast<int>(data); }
    template <typename T> typename std::enable_if<std::is_convertible<T, dword>::value, T>::type as() {
         return static_cast<T>(data);
    }
    template <typename T> typename std::enable_if<!std::is_convertible<T, dword>::value, T>::type as() {
        return reinterpret_cast<T>(data);
    }
    template <typename T> const T as() const { return reinterpret_cast<T>(data); }
    char *asPtr() { return reinterpret_cast<char *>(data); }
    const char *asPtr() const { return reinterpret_cast<char *>(data); }
    template <typename T> operator T*() const { return reinterpret_cast<T *>(data); }
    operator dword() const { return data; }
    Register& operator+=(size_t n) { data += n; return *this; }
    dword data;
};
#pragma pack(pop)

constexpr int k68kRegisterTotalSize = 15 * 4;

struct MenuBase;

extern "C" {
    extern Register D0, D1, D2, D3, D4, D5, D6, D7, A0, A1, A2, A3, A4, A5, A6;
    extern int16_t g_menuMusic;
    extern int16_t g_musicOff;
    extern int16_t g_inputControls;
    extern int16_t g_gameLength;
    extern int16_t g_autoReplays;
    extern int16_t g_autoSaveHighlights;
    extern int16_t g_allPlayerTeamsEqual;
    extern int16_t g_pitchType;
    extern int16_t g_commentary;
    extern int16_t g_chairmanScenes;
    extern int16_t g_spinBigS;
    extern byte g_upScanCode;
    extern byte g_downScanCode;
    extern byte g_leftScanCode;
    extern byte g_rightScanCode;
    extern byte g_fireScanCode;
    extern word skipIntro;
    extern word setupDatBuffer;
    extern char *dosMemLinAdr;
    extern char *dosMemOfs30000h;
    extern char *g_pitchPatterns;
    extern char *dosMemOfs4fc00h;
    extern char *dosMemOfs60c00h;
    extern const char aSensibleWorldOfSoccerV2_0[];
    extern dword selTeamsPtr;
    extern const char aSetup_dat[];
    extern char *linAdr384k;
    extern char *linAdr982k;
    extern char *linAdr2_6Mb;
    extern char *linAdr120k;
    extern void FadeOutToBlack();
    extern const char *partOneImages[];
    extern const char *partTwoImages[];
    extern word controlWord;
    extern word g_videoSpeedIndex;
    extern word g_joy2Status;
    extern word g_joy1Status;
    extern word g_joy1X;
    extern word g_joy1Y;
    extern word g_joy2X;
    extern word g_joy2Y;
    extern word someColorConversionFlag;
    extern const char aSprite_dat[];
    extern const char aCharset_dat[];
    extern dword *goalBasePtr;
    extern dword *nextGoalPtr;
    extern char hilFileBuffer[];
    extern dword currentHilBuffer[];
    extern char spritesIndex[];
    extern word randomSeed;
    extern void LoadTitleAndStartMusic();
    extern void FixupInitialCharset();
    extern void ChainFont();
    extern void Randomize2();
    extern char *vsPtr;
    extern dword screenWidth;
    extern word spriteFixupFlag;
    extern void InitMainMenu();
    extern void MenuProc();
    extern void TimerProc();
    extern word g_prevScanCode;
    extern word g_scanCode;
    extern word keyCount;
    extern char keyBuffer[10];
    extern word lastKey;
    extern byte convertedKey;
    extern const char convertKeysTable[110];
    extern void SetControlWord();
    extern word menuStatus;
    extern char g_currentMenu[6500];
    extern word g_exitMenu;
    extern MenuBase *g_currentMenuPtr;
    extern void RestorePreviousMenu();
    extern void StartMainGameLoop();
    extern char g_extension[];
    extern char g_pitchDatBuffer[10032];
    extern char skillsPerQuadrant[245];
    extern const char *ofsPitch1Dat;
    extern const char aPitch1_blk[];
    extern char g_fadePalette[768];
    extern word menuCycleTimer;
    extern word EGA_graphics;
    extern char g_workingPalette[768];
    extern word currentTick;
    extern word paused;
    extern word stoppageTimer;
    extern word timerBoolean;
    extern word bumpBigSFrame;
    extern void ClearBackground();
    extern const char aChairmanScenes[];
    extern const char aMenu_xmi[];
    extern const char aSwos_xmi[];
    extern word cdAudioPlaying;
    extern int16_t g_soundOff;
    extern word memAllOk;
    extern int commentarySampleHandle;
    extern void PlayIntroAnimation();
    extern void IntroFillSoundBuffer();
    extern const char aArcSoccer_bin[];
    extern char *soccerBinPtr;
    extern char *introCurrentSoundBuffer;
    extern char *soccerBinSoundChunkBuffer;
    extern char *soccerBinSoundDataPtr;
    extern char *introCurrentSoundBufferChunk;
    extern char *introScreenBuffer;
    extern byte introAborted;
    extern dword introFrameDataOffset;
    extern byte introFirstChunkLoaded;
    extern dword introNumFrames;
    extern dword introFrameDataChunkRemainder;
    extern FILE *soccerBinHandle;
    extern dword introSoundBufferIndex;
    extern byte introCurrentSoundBufferNum;
    extern dword introFrameDataSize;
    extern char *introCurrentFrameDataPtr;
    extern byte introAnimationTimer;
    extern byte introCountDownTimer;
    extern byte introWaitInterval;
    extern word g_midiPlaying;
    extern void ReadTimerDelta();
    extern word playHighlightFlag;
    extern void MainKeysCheck();
    extern void PlaySamples();
    extern word replayState;
    extern word hilSceneNumber;
    extern word numReplaysInHilFile;
    extern void RestoreGoalPointers();
    extern char hilStartOfGoalsBuffer[];
    extern dword *currentHilPtr;
    extern void FindStartingDword();
    extern word skipFade;
    extern void Player1StatusProc();
    extern void Player2StatusProc();
    extern void RestoreCameraPosition();
    extern byte pl1Fire;
    extern byte pl2Fire;
    extern word statsFireExit;
    extern void FadeIn();
    extern word cameraX;
    extern word cameraY;
    extern word savedCameraX;
    extern word savedCameraY;
    extern word oldCameraX;
    extern word oldCameraY;
    extern dword *currentGoalPtr;
    extern void ResetAnimatedPatternsForBothTeams();
    extern void InitSavedSprites();
    extern void InitBackground();
    extern void ScrollToCurrent();
    extern void MoveView();
    extern word hilLeftTeamGoals;
    extern word hilRightTeamGoals;
    extern void DrawAnimatedPatterns();
    extern word animPatternsState;
    extern void DrawSprite16Pixels();
    extern word noBigReplayLetter;
    extern byte deltaColor;
    extern word gameAborted;
    extern word userRequestedReplay;
    extern TeamGeneralInfo *teamDataPtr;
    extern word fadeAndSaveReplay;
    extern void FadeAndSaveReplay();
    extern word resetHilPtrFlag;
    extern void SortSprites();
    extern word numSpritesToRender;
    extern Player *sortedSprites[79];
    extern SpriteGraphics **spriteGraphicsPtr;
    extern Player big_S_Sprite;
    extern void SaveCoordinatesForHighlights();
    extern void DarkenRectangle();
    extern word playGame;
    extern void CommonMenuExit();
    extern const char aOptions[];
    extern const char aExit[];
    extern void ExitOptions();
    extern void SetExitMenuFlag();
    extern word controlsStatus;
    extern word showPrereleaseCounter;
    extern void CalcMenuEntryAddress();
    extern const char aFriendlyDiyGam[];
    extern const char aFixPitchType[];
    extern const char aAutoReplays[];
    extern const char aAllPlayerTeams[];
    extern const char aAutoSaveHighli[];
    extern void *gameLengthStrTable;
    extern void *pitchTypeStrTable;
    extern void *autoReplaysStrTable;
    extern void *allPlTeamsEqualStrTable;
    extern void *autoSaveHlStrTable;
    extern void *chairmanScenesStrTable;
    extern void ChangeGameLength();
    extern void ChangePitchType();
    extern void ChangeAutoReplays();
    extern void ChangeAllPlTeamsEqual();
    extern void ChangeAutoSaveHighlights();
    extern void ChangeChairmanScenes();
    extern const char aOn[];
    extern const char aOff[];
    extern const char aMenuMusic[];
    extern const char aCommentary[];
    extern const char aPlus[];
    extern const char aMinus[];
    extern void *menuMusicStrTable;
    extern void *commentaryStrTable;
    extern void ChangeCommentary();
    extern const char aCustom[];
    extern void ShowErrorMenu();
    extern void DrawMenuItem();
    extern void TryRestartingMusic();
    extern void DrawMenuText();
    extern void SetCurrentEntry();
    extern void ConvertMenu();
    extern word player1ClearFlag;
    extern const char smallCharsTable[];
    extern void Rand();
    extern byte seed;

    namespace SWOS {
        extern void DoUnchainSpriteInMenus_OnEnter();
        extern void InitGame_OnEnter();
        extern void ClearBackground_OnEnter();
        extern void PlayCrowdNoiseSample_OnEnter();
        extern void FadeOutToBlack_OnEnter();
        extern void FindStartingDword_OnEnter();
        extern void DrawBenchAndSubsMenu_OnEnter();
        extern void GameOver_OnEnter();
        extern void MenuProc_OnEnter();
        extern void SWOS();
        extern void ToMainGameLoop();
        extern void LoadFile();
        extern void WriteFile();
        extern void MainMenu();
        extern void FlipInMenu();
        extern void SetPalette();
        extern void ShowMenu();
        extern void SetPrevVideoModeEndProgram();
        extern void FindFiles();
        extern void FindFilesExtensionPresent();
        extern void Joy1SetStatus();
        extern void Joy2SetStatus();
        extern void ReadPitchFile();
        extern void WaitRetrace();
        extern void Flip();
        extern void DrawBackPattern();
        extern void InitMenuMusic();
        extern void PlayMidi();
        extern void StopMidiSequence();
        extern void CDROM_StopAudio();
        extern void IOCTL_CDROM_Read();
        extern void PlayChantSample22Khz();
        extern void PlaySfxSample22Khz();
        extern void PlayCommentarySample22Khz();
        extern void PlayRefereeWhistleSample();
        extern void FadeOutXmidi();
        extern void StopAudio();
        extern void IsSamplePlaying();
        extern void IntroEnsureFrameDataLoaded();
        extern void IntroDrawFrame();
        extern void JoyKeyOrCtrlPressed();
        extern void CloseSoccerBin();
        extern void PlayIntroSample();
        extern void PlayHighlightsLoop();
        extern void GetKey();
        extern void RenderReplayFrame();
        extern void PlayReplayLoop();
        extern void DrawSprites();
        extern void OptionsMenuSelected();
        extern void PrepareMenu();
    }
}
